In [1]:
import math

In [2]:
print(math.sqrt(16))

4.0

In [3]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [4]:
import pandas as pd
data = {'name': ['John', 'Anna', 'Peter'], 'Age':[20,30,40]}
df = pd.DataFrame(data)
print(df)

    name  Age
0   John   20
1   Anna   30
2  Peter   40